# Numpy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

1. a powerful N-dimensional array object
2. sophisticated (broadcasting) functions
3. tools for integrating C/C++ and Fortran code
4. useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Library documentation: http://www.numpy.org/

In [1]:
import numpy as np

## numpy.array

### Declare array using List as argument

In [2]:
arr= np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

##### Upcasting

In [3]:
arr= np.array([1.2,2,3,4])
arr

array([1.2, 2. , 3. , 4. ])

### Declare 2d-array using List as argument

In [4]:
arr2d =np.array([[1, 2], [3, 4]])
arr2d

array([[1, 2],
       [3, 4]])

##### Provide Minimum Dimensions

In [5]:
arr2d =np.array([1, 2, 3, 4], ndmin=2)
arr2d

array([[1, 2, 3, 4]])

In [6]:
arr3d= np.array([1, 2, 3], ndmin=3)
arr3d

array([[[1, 2, 3]]])

##### Type provided:

In [7]:
arrcmp= np.array([1, 2, 3], dtype=complex)
arrcmp

array([1.+0.j, 2.+0.j, 3.+0.j])

##### Data-type consisting of more than one element

In [8]:
dt = np.array([(1,2),(3,4)],dtype=[('a',int),('b',int)])
print dt['a']
print dt['b']

[1 3]
[2 4]


In [9]:
print type(dt)
dt

<type 'numpy.ndarray'>


array([(1, 2), (3, 4)], dtype=[('a', '<i8'), ('b', '<i8')])

In [10]:
dta = np.array([(1,2,9),(3,4,8)],dtype=[('id',int),('no',int),('pt', float)])
print dta['id']
print dta['no']
print dta['pt']

[1 3]
[2 4]
[9. 8.]


In [11]:
print type(dta)
dta

<type 'numpy.ndarray'>


array([(1, 2, 9.), (3, 4, 8.)],
      dtype=[('id', '<i8'), ('no', '<i8'), ('pt', '<f8')])

##### Creating an array from sub-classes:

In [12]:
arrsub= np.array(np.mat('1 2; 3 4'))
arrsub

array([[1, 2],
       [3, 4]])

In [13]:
arrsub = np.array(np.mat('1 2; 3 4'), subok=True)
arrsub

matrix([[1, 2],
        [3, 4]])

## numpy.arange
Return evenly spaced values within a given interval

Uses step size: difference between numbers  

In [14]:
print np.arange(3) # stop
print np.arange(3,7) # start, stop
print np.arange(3,7,2) #start, stop, step

[0 1 2]
[3 4 5 6]
[3 5]


## numpy.linspace
Return evenly spaced numbers over a specified interval.

Returns number of samples specified 

In [15]:
print np.linspace(2.0, 3.0, num=5)
print np.linspace(2.0, 3.0, num=5, endpoint=False) #endpoint:include the ending digit or not
print np.linspace(2.0, 3.0, num=5, retstep=True)

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


## numpy.logspace

In [16]:
print np.logspace(2.0, 3.0, num=4) # 10^2 to 10^3
print np.logspace(2.0, 3.0, num=4, base=2.0) # 2^2 to 2^3
print np.logspace(2.0, 3.0, num=4, endpoint=False)


[ 100.          215.443469    464.15888336 1000.        ]
[4.         5.0396842  6.34960421 8.        ]
[100.         177.827941   316.22776602 562.34132519]


## numpy.geomspace
Return numbers spaced evenly on a log scale (a geometric progression).

In [17]:
print np.geomspace(1, 1000, num=4)
print np.geomspace(1, 1000, num=3, endpoint=False)
print np.geomspace(1, 1000, num=4, endpoint=False)
print np.geomspace(1, 256, num=9)

[   1.   10.  100. 1000.]
[  1.  10. 100.]
[  1.           5.62341325  31.6227766  177.827941  ]
[  1.   2.   4.   8.  16.  32.  64. 128. 256.]


In [18]:
print np.geomspace(1000, 1, num=4)
print np.geomspace(-1000, -1, num=4)
print np.geomspace(1j, 1000j, num=4)  # Straight line
print np.geomspace(-1+0j, 1+0j, num=5)  # Circle

[1000.  100.   10.    1.]
[-1000.  -100.   -10.    -1.]
[0.   +1.j 0.  +10.j 0. +100.j 0.+1000.j]
[-1.00000000e+00+1.22464680e-16j -7.07106781e-01+7.07106781e-01j
  6.12323400e-17+1.00000000e+00j  7.07106781e-01+7.07106781e-01j
  1.00000000e+00+0.00000000e+00j]


## numpy.mgrid
nd_grid instance which returns a dense multi-dimensional “meshgrid”.

In [19]:
x,y= np.mgrid[0:5,0:5]
print x
print '-------'
print y

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
-------
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [20]:
a=np.mgrid[0:5,0:5]
a

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [21]:
b= np.mgrid[-1:1:5j] # 5j is step size
b

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [22]:
c = np.mgrid[0:5:2,0:5:2]
c

array([[[0, 0, 0],
        [2, 2, 2],
        [4, 4, 4]],

       [[0, 2, 4],
        [0, 2, 4],
        [0, 2, 4]]])

## numpy.random

##### Simple random data
**rand(d0, d1, ..., dn)**     Random values in a given shape.<br/>
**randn(d0, d1, ..., dn)**	Return a sample (or samples) from the “standard normal” distribution.<br/>
**randint(low[, high, size, dtype])**	Return random integers from low (inclusive) to high (exclusive).<br/>
**random_integers(low[, high, size])****	Random integers of type np.int between low and high, inclusive.<br/>
**random_sample([size])**	Return random floats in the half-open interval [0.0, 1.0).<br/>
**random([size])**	Return random floats in the half-open interval [0.0, 1.0).<br/>
**ranf([size])**	Return random floats in the half-open interval [0.0, 1.0).<br/>
**sample([size])**	Return random floats in the half-open interval [0.0, 1.0).<br/>
**choice(a[, size, replace, p])**	Generates a random sample from a given 1-D array<br/>
**bytes(length)**	Return random bytes.<br/>
##### Permutations
**shuffle(x)**	Modify a sequence in-place by shuffling its contents.<br/>
**permutation(x)**	Randomly permute a sequence, or return a permuted range.
##### Distributions
**beta(a, b[, size])**	Draw samples from a Beta distribution.<br/>
**binomial(n, p[, size])**	Draw samples from a binomial distribution.<br/>
**chisquare(df[, size])**	Draw samples from a chi-square distribution.<br/>
**dirichlet(alpha[, size])**	Draw samples from the Dirichlet distribution.<br/>
**exponential([scale, size])**	Draw samples from an exponential distribution.<br/>
**f(dfnum, dfden[, size])**	Draw samples from an F distribution.<br/>
**gamma(shape[, scale, size])**	Draw samples from a Gamma distribution.<br/>
**geometric(p[, size])**	Draw samples from the geometric distribution.<br/>
**gumbel([loc, scale, size])**	Draw samples from a Gumbel distribution.<br/>
**hypergeometric(ngood, nbad, nsample[, size])**	Draw samples from a Hypergeometric distribution.<br/>
**laplace([loc, scale, size])**	Draw samples from the Laplace or double exponential distribution with specified location (or mean) and scale (decay).<br/><br/>
**logistic([loc, scale, size])**	Draw samples from a logistic distribution.<br/>
**lognormal([mean, sigma, size])**	Draw samples from a log-normal distribution.<br/>
**logseries(p[, size])**	Draw samples from a logarithmic series distribution.<br/>
**multinomial(n, pvals[, size])**	Draw samples from a multinomial distribution.<br/>
**multivariate_normal(mean, cov[, size, ...)**	Draw random samples from a multivariate normal distribution.<br/>
**negative_binomial(n, p[, size])**	Draw samples from a negative binomial distribution.<br/>
**noncentral_chisquare(df, nonc[, size])**	Draw samples from a noncentral chi-square distribution.<br/>
**noncentral_f(dfnum, dfden, nonc[, size])**	Draw samples from the noncentral F distribution.<br/>
**normal([loc, scale, size])**	Draw random samples from a normal (Gaussian) distribution.<br/>
**pareto(a[, size])**	Draw samples from a Pareto II or Lomax distribution with specified shape.<br/>
**poisson([lam, size])**	Draw samples from a Poisson distribution.<br/>
**power(a[, size])**	Draws samples in [0, 1] from a power distribution with positive exponent a - 1.<br/>
**rayleigh([scale, size])**	Draw samples from a Rayleigh distribution.<br/>
**standard_cauchy([size])**	Draw samples from a standard Cauchy distribution with mode = 0.<br/>
**standard_exponential([size])**	Draw samples from the standard exponential distribution.<br/>
**standard_gamma(shape[, size])**	Draw samples from a standard Gamma distribution.<br/>
**standard_normal([size])**	Draw samples from a standard Normal distribution (mean=0, stdev=1).<br/>
**standard_t(df[, size])**	Draw samples from a standard Student’s t distribution with df degrees of freedom.<br/>
**triangular(left, mode, right[, size])**	Draw samples from the triangular distribution over the interval [left, right].<br/>
**uniform([low, high, size])**	Draw samples from a uniform distribution.<br/>
**vonmises(mu, kappa[, size])**	Draw samples from a von Mises distribution.<br/>
**wald(mean, scale[, size])**	Draw samples from a Wald, or inverse Gaussian, distribution.<br/>
**weibull(a[, size])**	Draw samples from a Weibull distribution.<br/>
**zipf(a[, size])**	Draw samples from a Zipf distribution.<br/>
##### Random generator
**RandomState**	Container for the Mersenne Twister pseudo-random number generator.<br/>
**seed([seed])**	Seed the generator.<br/>
**get_state()**	Return a tuple representing the internal state of the generator.<br/>
**set_state(state)**	Set the internal state of the generator from a tuple.<br/>



In [23]:
np.random.rand(5,5)

array([[0.03590534, 0.76895749, 0.11079776, 0.39914742, 0.97257186],
       [0.01137565, 0.13489609, 0.13068536, 0.54301819, 0.8341808 ],
       [0.94835447, 0.16255083, 0.18256063, 0.69588574, 0.45685803],
       [0.20514503, 0.9746235 , 0.80301175, 0.49107274, 0.70057068],
       [0.55866186, 0.31072236, 0.35045403, 0.68266708, 0.81003529]])

In [24]:
np.random.randn(5,5)

array([[ 0.54723497,  0.34725319,  0.10050899, -0.78587617, -0.39509245],
       [ 0.49136771,  0.36267967,  1.00652707,  0.1228991 , -0.73526949],
       [ 0.84955385,  0.77866812, -0.34714541, -0.49863271,  0.80256192],
       [ 1.06197176, -1.2150686 ,  1.08683232,  0.2200444 ,  2.20300031],
       [-0.70098743,  0.08300593,  0.19842754,  1.19555242,  0.34003863]])

In [25]:
np.random.randint(1,5)

3

## numpy.diag
Extract a diagonal or construct a diagonal array.

In [26]:
dg=np.diag([1,2,3,4])
dg

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [27]:
dg2= np.diag([1,2,3,4,5], k=-1)
dg2

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

In [28]:
dg3= np.diag([1,2,3,4,5], k=2)
dg3

array([[0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

## Misc

##### Attributes

In [29]:
dg3.size

49

In [30]:
dg3.itemsize

8

In [31]:
dg3.nbytes

392

In [32]:
dg3.ndim

2

In [33]:
dg3[1]

array([0, 0, 0, 2, 0, 0, 0])

In [34]:
dg3[1,1]

0

In [35]:
dg[0,0], dg3[2,4]

(1, 3)

##### Assign new value

In [36]:
dg3[0,0]= 99
dg3

array([[99,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  2,  0,  0,  0],
       [ 0,  0,  0,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  0,  0,  5],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [37]:
dg3[2,:]= 33
dg3

array([[99,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  2,  0,  0,  0],
       [33, 33, 33, 33, 33, 33, 33],
       [ 0,  0,  0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  0,  0,  5],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

##### Slicing Arrays 

In [38]:
A = np.array([1,2,3,4,5,6,7,8,9])
A[1:4]

array([2, 3, 4])

##### Array Manipulation 

In [39]:
A = np.array([[n+m*10 for n in range(1,5)] for m in range(2,7)])
A

array([[21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54],
       [61, 62, 63, 64]])

In [40]:
row_indices = [2, 3, 4]
A[row_indices]

array([[41, 42, 43, 44],
       [51, 52, 53, 54],
       [61, 62, 63, 64]])

In [41]:
row_indices = [2, 1, 4]
A[row_indices]

array([[41, 42, 43, 44],
       [31, 32, 33, 34],
       [61, 62, 63, 64]])

In [42]:
# index masking
B = np.array([n for n in range(6)])
row_mask = np.array([True, False, True, False, False, True])
B[row_mask]

array([0, 2, 5])

##### Reshape Arrays

In [43]:
array= np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
mat = array.reshape(3,3)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
mat.shape

(3, 3)

In [46]:
m,n = mat.shape

In [47]:
B = mat.reshape((1,n*m))
B

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [48]:
fltarr= mat.flatten()
fltarr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Insert a dimension in an array

In [49]:
dimar = np.array([1,2,3])
dimar[:, np.newaxis], dimar[:,np.newaxis].shape, dimar[np.newaxis,:].shape

(array([[1],
        [2],
        [3]]), (3, 1), (1, 3))

In [50]:
np.repeat(dimar, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [51]:
np.tile(dimar,4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [52]:
a2 = np.array([4, 6, 7, 6, 4])

In [53]:
nar= np.concatenate((dimar, a2), axis=0)
nar

array([1, 2, 3, 4, 6, 7, 6, 4])

In [54]:
nar.shape

(8,)

In [55]:
m= nar.shape
newNar=nar.reshape(m[0],1)
newNar

array([[1],
       [2],
       [3],
       [4],
       [6],
       [7],
       [6],
       [4]])

##### Deep Copy

In [56]:
B = np.copy(newNar)
B

array([[1],
       [2],
       [3],
       [4],
       [6],
       [7],
       [6],
       [4]])

## Linear Algebra 

In [57]:
a1= np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Adding element to array

In [58]:
a1+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

##### Array Multiplication

In [59]:
a1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
a1*a1

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

##### Dot Product

In [61]:
np.dot(a1,a1)

285

##### Array Transpose

In [62]:
a1_t= a1.T
a1_t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Inner Product

In [63]:
a1*a1_t

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

##### Numpy Array and Numpy Matrices

**Note**:
Numpy matrices are strictly 2-dimensional, while numpy arrays (ndarrays) are N-dimensional. Matrix objects are a subclass of ndarray, so they inherit all the attributes and methods of ndarrays.

Matrix multiplication: If a1 and a2 are matrices, then **a1\*a2** is their *matrix* product.

ndarray multiplication : If a and b are matrices, then **np.dot(a,b)** is their *matrix* product.


In [64]:
a1=np.mat('4 3; 2 1')
a2=np.mat('1 2; 3 4')
print(a1)
print(a2)
print(a1*a2)

[[4 3]
 [2 1]]
[[1 2]
 [3 4]]
[[13 20]
 [ 5  8]]


In [65]:
a=np.array([[4, 3], [2, 1]])
b=np.array([[1, 2], [3, 4]])
print np.dot(a,b)

[[13 20]
 [ 5  8]]


##### ** operator

In [66]:
a=np.mat('4 3; 2 1')
b=np.array([[4, 3], [2, 1]])

print a**2 # is nothing but a*a
print "---------"
print b**2 # is nothing but, each element squared

[[22 15]
 [10  7]]
---------
[[16  9]
 [ 4  1]]


In [67]:
print a.size
print b.size

4
4


### Matrix Manipulation 

In [68]:
m= np.mat(np.arange(1,10))
m

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

###### Reshape Matrix

In [69]:
m = m.reshape(3,3)
m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

##### Matrix Transpose

In [70]:
m_t= m.T
m_t

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

##### Matrix Inverse

In [71]:
m_i=m.I
m_i

matrix([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
        [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
        [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

##### Matrix Multiplication

In [72]:
m*m_t

matrix([[ 14,  32,  50],
        [ 32,  77, 122],
        [ 50, 122, 194]])

#####  Complex Number Matrix

In [73]:
C = np.matrix([[1j, 2j], [3j, 4j]])
C

matrix([[0.+1.j, 0.+2.j],
        [0.+3.j, 0.+4.j]])

##### Conjugate of Matrix

In [74]:
C_c=np.conjugate(C)
C_c

matrix([[0.-1.j, 0.-2.j],
        [0.-3.j, 0.-4.j]])

## Statistics

In [75]:
arr = np.arange(5,20)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

##### Mean

In [76]:
np.mean(arr[:5])

7.0

##### Standard Deviation 

In [77]:
np.std(arr[:6])

1.707825127659933

##### Variance

In [78]:
np.var(arr[:6])

2.9166666666666665

##### Maximum and Minimum

In [79]:
arr[:7].max() , arr[4:].min()

(11, 9)

#### Sum and Product

In [80]:
np.sum(arr[:3]), np.prod(arr[:3])

(18, 210)

##### Cummulative Sum

In [81]:
np.cumsum(arr[:3])

array([ 5, 11, 18])

##### Cummulative Product 

In [82]:
np.cumprod(arr[:3])

array([  5,  30, 210])

##### Sum of Diagonal in Matrix

In [83]:
m_t

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [84]:
np.trace(m_t)

15

### Matrix and Stats

In [85]:
mat = np.random.rand(3, 3)
mat

array([[0.43099794, 0.76914586, 0.1466162 ],
       [0.05682999, 0.97494543, 0.85160398],
       [0.21287962, 0.88018894, 0.92349639]])

##### Maximum and Minimum

In [86]:
mat.max(), mat.min()

(0.9749454264736949, 0.056829992035629884)

In [87]:
mat.max(axis=0)

array([0.43099794, 0.97494543, 0.92349639])

In [88]:
mat.max(axis=1)

array([0.76914586, 0.97494543, 0.92349639])

Last Updated: June 16, 2018